# nixpacks.toml

providers = ["python"]

[phases.install]
# Install system-level packages required by Frappe/Python
aptPkgs = ["wkhtmltopdf", "mariadb-client", "python3-pip", "python3-dev", "build-essential"]

# Use pip to install Frappe's command-line tool
cmds = ["pip install frappe-bench"]

[start]
# The command to run a Frappe development server
cmd = "bench start"
